jobs:
    build:
        runs-on: ubuntu-latest
        steeps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
            - name: Generate Headers
              run: chmod +x gradlew && ./gradlew compileJava
            - name: Build
              run: cross/setup_docker.sh
            - name: Archive NativeLib artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: ${{env.CROSS}}
                  path: |
                    native/cmake-build-debug/Release